"""
Django settings for commitrush project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ctkrc2)9-(yrqd)eq0d97$6a_co973x7$t-x!q7!a@*(n!afsk'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1],testserver').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Domain apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# REST Framework default configuration (PRD §16, §19, §20, Plan M3-T5)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '100/minute',
        'projects_list': '100/minute',
        'issues_list': '100/minute',
    },
}

# CORS configuration for frontend local development
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'commitrush.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'commitrush.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# PostgreSQL is the authoritative application database for CommitRush.
# Connection parameters are configured via environment variables.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'commitrush'),
        'USER': os.environ.get('DB_USER', 'commitrush'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# GitHub OAuth Configuration (PRD §8.1, §13.1, §19, plan.md M1-T3)
GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
GITHUB_REDIRECT_URI = os.environ.get(
    'GITHUB_REDIRECT_URI',
    'http://localhost:8000/auth/github/callback/'
)
# Minimum scope per PRD §13.1 & plan.md M1-T3. AMB-4 (email scope) remains open.
GITHUB_OAUTH_SCOPE = os.environ.get('GITHUB_OAUTH_SCOPE', 'read:user')

# GitHub REST API Service Token (PRD §13.6, §19, plan.md M2-T1)
GITHUB_API_TOKEN = os.environ.get('GITHUB_API_TOKEN', '')

# GitHub Webhook Secret (PRD §13.2, §16, §19, plan.md M4-T1)
GITHUB_WEBHOOK_SECRET = os.environ.get('GITHUB_WEBHOOK_SECRET', '')

# Frontend URLs for OAuth redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
FRONTEND_AUTH_REDIRECT_URL = os.environ.get('FRONTEND_AUTH_REDIRECT_URL', f'{FRONTEND_URL}/')

# Session & Cookie Security (PRD §19)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000'
    ).split(',')
    if origin.strip()
]

# Celery Configuration (PRD §10.1, §13.6, plan.md M2-T4, M4-T3)
# Redis is the broker and result backend. Configuration is backed by environment variables.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', os.environ.get('REDIS_URL', 'redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = {
    'webhooks': {
        'exchange': 'webhooks',
        'routing_key': 'webhooks',
    },
    'validation': {
        'exchange': 'validation',
        'routing_key': 'validation',
    },
    'sync': {
        'exchange': 'sync',
        'routing_key': 'sync',
    },
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
}
CELERY_TASK_ROUTES = {
    'core.tasks.sync_repository_task': {'queue': 'sync'},
    'core.tasks.process_webhook_event_task': {'queue': 'webhooks'},
    'core.tasks.reconcile_recent_repositories_task': {'queue': 'sync'},
    'core.tasks.reconcile_all_repositories_nightly_task': {'queue': 'sync'},
    'core.tasks.validate_contribution_task': {'queue': 'validation'},
    'core.tasks.requeue_stale_contributions_task': {'queue': 'sync'},
}

# Reconciliation & Worker Configuration (PRD §11.2, §12.4, §13.4, plan.md M4-T5, M5-T3)
RECONCILIATION_RECENT_WINDOW_MINUTES = int(os.environ.get('RECONCILIATION_RECENT_WINDOW_MINUTES', '15'))
WORKER_LOCK_TIMEOUT_MINUTES = int(os.environ.get('WORKER_LOCK_TIMEOUT_MINUTES', '10'))

CELERY_BEAT_SCHEDULE = {
    'reconcile-recent-repositories-15min': {
        'task': 'core.tasks.reconcile_recent_repositories_task',
        'schedule': float(os.environ.get('RECONCILIATION_BEAT_SECONDS', 15 * 60)),  # Every 15 minutes by default
    },
    'reconcile-all-repositories-nightly': {
        'task': 'core.tasks.reconcile_all_repositories_nightly_task',
        'schedule': float(os.environ.get('RECONCILIATION_NIGHTLY_SECONDS', 24 * 60 * 60)),  # Daily / nightly by default
    },
    'requeue-stale-contributions-5min': {
        'task': 'core.tasks.requeue_stale_contributions_task',
        'schedule': float(os.environ.get('RECOVERY_SWEEP_SECONDS', 5 * 60)),  # Every 5 minutes by default
    },
}
