"""
Django settings for commitrush project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present (local dev)
def _load_env(env_path: Path):
    if not env_path.is_file():
        return
    try:
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith('#') or '=' not in stripped:
                    continue
                k, _, v = stripped.partition('=')
                k = k.strip()
                v = v.strip().strip("'\"")
                if k and k not in os.environ:
                    os.environ[k] = v
    except OSError:
        pass

_load_env(BASE_DIR / '.env')
_load_env(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ctkrc2)9-(yrqd)eq0d97$6a_co973x7$t-x!q7!a@*(n!afsk'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1')

if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set to a secure, random string (min 50 chars) in production when DEBUG=False."
    )

allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS')
if allowed_hosts_raw:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_raw.split(',') if h.strip()]
    if 'testserver' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('testserver')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Domain apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
# WhiteNoise serves static assets directly from WSGI in production; bypassed during test runs
if not (len(sys.argv) > 1 and sys.argv[1] == 'test'):
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

MIDDLEWARE.extend([
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
])

# REST Framework default configuration (PRD §16, §19, §20, Plan M3-T5, M7-T1)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '100/minute',
        'projects_list': '100/minute',
        'issues_list': '100/minute',
        'leaderboard_list': '100/minute',
        'profile_detail': '100/minute',
        'stats_list': '120/minute',
        'admin_sync': '10/minute',
        'admin_controls': '60/minute',
    },
}

# Caching Configuration (PRD §10.2, §20, plan.md M7-T1)
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache')
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CACHES = {
    'default': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': REDIS_URL if 'redis' in CACHE_BACKEND.lower() else os.environ.get('CACHE_LOCATION', 'commitrush-cache'),
        'TIMEOUT': 60,
    }
}

# CORS configuration (PRD §16, §19)
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173' if DEBUG else ''
    ).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = [
    'X-CSRFToken',
    'Content-Type',
]


ROOT_URLCONF = 'commitrush.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'commitrush.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# PostgreSQL is the authoritative application database for CommitRush.
# Connection parameters are configured via environment variables.

DATABASE_URL = os.environ.get('DATABASE_URL')
USE_SQLITE_ENV = os.environ.get('USE_SQLITE')

# When DATABASE_URL is present, PostgreSQL takes precedence over SQLite unless explicitly pointing to a sqlite scheme.
if DATABASE_URL:
    USE_SQLITE = False
elif USE_SQLITE_ENV is not None:
    USE_SQLITE = USE_SQLITE_ENV.lower() in ('true', '1', 'yes') or os.environ.get('DB_ENGINE') == 'sqlite3'
else:
    USE_SQLITE = not bool(os.environ.get('DB_HOST') or os.environ.get('DB_NAME'))

if DATABASE_URL:
    import urllib.parse
    parsed_db = urllib.parse.urlparse(DATABASE_URL)
    is_sqlite_url = parsed_db.scheme.startswith('sqlite')
    if is_sqlite_url:
        db_path = parsed_db.path.lstrip('/') or 'db.sqlite3'
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / db_path,
                'OPTIONS': {'timeout': 60},
            }
        }
    else:
        # Handles postgresql://, postgres://, and related PostgreSQL URL schemes
        query_params = urllib.parse.parse_qs(parsed_db.query)
        db_options = {}
        for qk, qvals in query_params.items():
            if qvals:
                db_options[qk] = qvals[-1]

        # Ensure SSL for Neon PostgreSQL connections
        # Priority: explicit DB_SSLMODE env > URL query parameter (?sslmode=...) > automatic 'require' for .neon.tech
        sslmode = os.environ.get('DB_SSLMODE') or db_options.get('sslmode')
        if not sslmode and parsed_db.hostname and 'neon.tech' in parsed_db.hostname:
            sslmode = 'require'
        if sslmode:
            db_options['sslmode'] = sslmode

        db_name = urllib.parse.unquote(parsed_db.path.lstrip('/')) if parsed_db.path else ''
        db_user = urllib.parse.unquote(parsed_db.username) if parsed_db.username else ''
        db_password = urllib.parse.unquote(parsed_db.password) if parsed_db.password else ''

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': parsed_db.hostname or 'localhost',
                'PORT': str(parsed_db.port or 5432),
                'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
                'CONN_HEALTH_CHECKS': os.environ.get('DB_CONN_HEALTH_CHECKS', 'True').lower() in ('true', '1'),
                'OPTIONS': db_options,
            }
        }
elif USE_SQLITE and not os.environ.get('DB_HOST') and not os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 60,
            },
        }
    }
else:
    db_options = {}
    db_host = os.environ.get('DB_HOST', 'localhost')
    db_sslmode = os.environ.get('DB_SSLMODE')
    if not db_sslmode and 'neon.tech' in db_host:
        db_sslmode = 'require'
    if db_sslmode:
        db_options['sslmode'] = db_sslmode

    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('DB_NAME', 'commitrush'),
            'USER': os.environ.get('DB_USER', 'commitrush'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': db_host,
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            'CONN_HEALTH_CHECKS': os.environ.get('DB_CONN_HEALTH_CHECKS', 'True').lower() in ('true', '1'),
            'OPTIONS': db_options,
        }
    }

db_sslmode = os.environ.get('DB_SSLMODE')
if db_sslmode and 'postgresql' in DATABASES['default']['ENGINE']:
    DATABASES['default'].setdefault('OPTIONS', {})['sslmode'] = db_sslmode


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Event Official Timezone: Asia/Kolkata (IST), resetting at 00:00 IST every day
TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Kolkata')
EVENT_TIMEZONE = os.environ.get('EVENT_TIMEZONE', 'Asia/Kolkata')
EVENT_START_DATE = os.environ.get('EVENT_START_DATE', '2026-09-22')
EVENT_END_DATE = os.environ.get('EVENT_END_DATE', '2026-10-31')
EVENT_TARGET_BRANCH = os.environ.get('EVENT_TARGET_BRANCH', 'main')
EVENT_DAILY_POINTS_CAP = int(os.environ.get('EVENT_DAILY_POINTS_CAP', '120'))

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
try:
    STATIC_ROOT.mkdir(parents=True, exist_ok=True)
except OSError:
    pass
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': os.environ.get(
            'EMAIL_BACKEND',
            'django.core.mail.backends.smtp.EmailBackend' if not DEBUG else 'django.core.mail.backends.console.EmailBackend'
        ),
    },
}


# GitHub OAuth Configuration (PRD §8.1, §13.1, §19, plan.md M1-T3)
GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
GITHUB_REDIRECT_URI = os.environ.get(
    'GITHUB_REDIRECT_URI',
    'http://localhost:8000/auth/github/callback/' if DEBUG else ''
).strip()
# Minimum scope per PRD §13.1 & plan.md M1-T3. AMB-4 (email scope) remains open.
GITHUB_OAUTH_SCOPE = os.environ.get('GITHUB_OAUTH_SCOPE', 'read:user')

# GitHub REST API Service Token (PRD §13.6, §19, plan.md M2-T1)
GITHUB_API_TOKEN = os.environ.get('GITHUB_API_TOKEN', '')

# GitHub Webhook Secret (PRD §13.2, §16, §19, plan.md M4-T1)
GITHUB_WEBHOOK_SECRET = os.environ.get('GITHUB_WEBHOOK_SECRET', '')

# Frontend URLs for OAuth redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173' if DEBUG else '').strip()
FRONTEND_AUTH_REDIRECT_URL = os.environ.get(
    'FRONTEND_AUTH_REDIRECT_URL',
    f'{FRONTEND_URL}/profile' if FRONTEND_URL else '/profile'
).strip()

# Ensure FRONTEND_URL is included in CORS allowed origins
if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

# Session & Cookie Security (PRD §19)
SESSION_COOKIE_HTTPONLY = True
# In decoupled deployments (e.g. Vercel frontend + Render backend), cross-site fetch
# requests require SameSite=None and Secure=True, otherwise browsers drop the session cookie.
_default_cookie_samesite = 'None' if not DEBUG else 'Lax'
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE') or _default_cookie_samesite
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() in ('true', '1')
SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN') or None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE') or _default_cookie_samesite
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() in ('true', '1')

# HTTP Security Headers (HSTS, SSL redirect, framing, content sniffing)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False').lower() in ('true', '1')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False').lower() in ('true', '1')
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True' if not DEBUG else 'False').lower() in ('true', '1')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000' if DEBUG else ''
    ).split(',')
    if origin.strip()
]
if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
if GITHUB_REDIRECT_URI:
    import urllib.parse
    parsed_redirect = urllib.parse.urlparse(GITHUB_REDIRECT_URI)
    if parsed_redirect.scheme and parsed_redirect.netloc:
        redirect_origin = f"{parsed_redirect.scheme}://{parsed_redirect.netloc}"
        if redirect_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(redirect_origin)

# Celery & Redis Configuration (PRD §10.1, §13.6, plan.md M2-T4, M4-T3)
# Redis is the broker, cache, and distributed semaphore backend. Configuration is backed by environment variables.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = {
    'webhooks': {
        'exchange': 'webhooks',
        'routing_key': 'webhooks',
    },
    'validation': {
        'exchange': 'validation',
        'routing_key': 'validation',
    },
    'merge': {
        'exchange': 'merge',
        'routing_key': 'merge',
    },
    'sync': {
        'exchange': 'sync',
        'routing_key': 'sync',
    },
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
    'analytics': {
        'exchange': 'analytics',
        'routing_key': 'analytics',
    },
}
CELERY_TASK_ROUTES = {
    'core.tasks.sync_repository_task': {'queue': 'sync'},
    'core.tasks.process_webhook_event_task': {'queue': 'webhooks'},
    'core.tasks.reconcile_recent_repositories_task': {'queue': 'sync'},
    'core.tasks.reconcile_all_repositories_nightly_task': {'queue': 'sync'},
    'core.tasks.validate_contribution_task': {'queue': 'validation'},
    'core.tasks.requeue_stale_contributions_task': {'queue': 'sync'},
    'core.tasks.merge_contribution_task': {'queue': 'merge'},
    'core.tasks.process_merge_queue_task': {'queue': 'merge'},
    'core.tasks.refresh_event_stats_task': {'queue': 'analytics'},
}

# Semaphore & Concurrency Settings (PRD §10.1, §12.3, Plan M6-T1)
MERGE_SEMAPHORE_KEY = os.environ.get('MERGE_SEMAPHORE_KEY', 'commitrush:semaphore:merge')
MERGE_SEMAPHORE_TTL = int(os.environ.get('MERGE_SEMAPHORE_TTL', '120'))

# Reconciliation & Worker Configuration (PRD §11.2, §12.4, §13.4, plan.md M4-T5, M5-T3)
RECONCILIATION_RECENT_WINDOW_MINUTES = int(os.environ.get('RECONCILIATION_RECENT_WINDOW_MINUTES', '15'))
WORKER_LOCK_TIMEOUT_MINUTES = int(os.environ.get('WORKER_LOCK_TIMEOUT_MINUTES', '10'))

CELERY_BEAT_SCHEDULE = {
    'reconcile-recent-repositories-15min': {
        'task': 'core.tasks.reconcile_recent_repositories_task',
        'schedule': float(os.environ.get('RECONCILIATION_BEAT_SECONDS', 15 * 60)),  # Every 15 minutes by default
    },
    'reconcile-all-repositories-nightly': {
        'task': 'core.tasks.reconcile_all_repositories_nightly_task',
        'schedule': float(os.environ.get('RECONCILIATION_NIGHTLY_SECONDS', 24 * 60 * 60)),  # Daily / nightly by default
    },
    'requeue-stale-contributions-5min': {
        'task': 'core.tasks.requeue_stale_contributions_task',
        'schedule': float(os.environ.get('RECOVERY_SWEEP_SECONDS', 5 * 60)),  # Every 5 minutes by default
    },
    'process-merge-queue-10sec': {
        'task': 'core.tasks.process_merge_queue_task',
        'schedule': float(os.environ.get('MERGE_QUEUE_BEAT_SECONDS', 10)),  # Every 10 seconds by default
    },
    'refresh-event-stats-60sec': {
        'task': 'core.tasks.refresh_event_stats_task',
        'schedule': float(os.environ.get('STATS_REFRESH_BEAT_SECONDS', 60)),  # Every 60 seconds by default
    },
}

# Production Logging Configuration (PRD §19, §23)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{name}:{lineno}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': os.environ.get('APP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

