# Generated by Django 6.1.1 on 2026-09-15 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_concurrency', models.IntegerField(default=5, help_text='Maximum concurrent merge-bot operations')),
                ('max_contributions_per_day', models.IntegerField(default=5, help_text='Daily contribution credit cap per participant')),
                ('max_points_per_day', models.IntegerField(default=500, help_text='Daily points cap per participant')),
                ('merge_paused', models.BooleanField(default=False, help_text='Emergency control: pause all merge queue operations')),
                ('validation_paused', models.BooleanField(default=False, help_text='Emergency control: pause contribution validation pipeline')),
                ('submissions_paused', models.BooleanField(default=False, help_text='Emergency control: pause accepting new webhook submissions')),
                ('leaderboard_frozen', models.BooleanField(default=False, help_text='Emergency control: freeze public leaderboard rankings')),
                ('event_status', models.CharField(default='pending', help_text='Event status (e.g., pending, active, ended)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='GitHub label name', max_length=255, unique=True)),
                ('color', models.CharField(blank=True, default='', help_text='Label hex color code', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(help_text='GitHub X-GitHub-Delivery header identifier', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='GitHub event type (e.g., pull_request, issues)', max_length=100)),
                ('payload', models.JSONField(help_text='Raw webhook JSON payload from GitHub')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when asynchronous processing completed', null=True)),
                ('processing_error', models.TextField(blank=True, default='', help_text='Error details if processing failed')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_issue_id', models.BigIntegerField(help_text='Immutable GitHub Issue ID', unique=True)),
                ('number', models.IntegerField(help_text='Issue number in the GitHub repository')),
                ('title', models.CharField(help_text='Issue title', max_length=1024)),
                ('points', models.IntegerField(default=50, help_text='Points awarded for resolving this issue')),
                ('difficulty', models.CharField(blank=True, default='', help_text='Difficulty tier (e.g., beginner, intermediate, advanced)', max_length=50)),
                ('category', models.CharField(blank=True, default='', help_text='Issue category/domain (e.g., backend, frontend, docs)', max_length=100)),
                ('status', models.CharField(default='open', help_text='Issue status: open, closed, or disabled', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this issue is highlighted in explorer UI')),
                ('labels', models.ManyToManyField(blank=True, help_text='Cached GitHub issue labels', related_name='issues', to='core.issuelabel')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(help_text='Immutable GitHub User ID', unique=True)),
                ('github_username', models.CharField(help_text='GitHub username cached at login', max_length=255)),
                ('avatar_url', models.URLField(blank=True, help_text='Avatar URL cached from GitHub profile', max_length=1024, null=True)),
                ('is_suspended', models.BooleanField(default=False, help_text='Suspended participants cannot be awarded points')),
                ('total_points', models.IntegerField(default=0, help_text='Denormalized total points counter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyContributionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of activity (UTC)')),
                ('contributions_count', models.IntegerField(default=0, help_text='Number of credited contributions on this date')),
                ('points_count', models.IntegerField(default=0, help_text='Total points awarded on this date')),
                ('participant', models.ForeignKey(help_text='Participant tracked', on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', help_text='State machine status: PENDING, QUEUED, UNDER_REVIEW, APPROVED, MERGING, MERGED, REJECTED, FLAGGED, RETRY', max_length=50)),
                ('sub_status', models.CharField(blank=True, default='', help_text='Sub-status or phase (e.g., VALIDATING)', max_length=50)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when worker locked contribution for processing', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of transient retry attempts')),
                ('flagged_reason', models.TextField(blank=True, default='', help_text='Explanation if held for admin review')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when validation succeeded and approved for merge queue', null=True)),
                ('merged_at', models.DateTimeField(blank=True, help_text='Timestamp when confirmed merged', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated timestamp')),
                ('issue', models.ForeignKey(help_text='Tracked issue being addressed', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.issue')),
                ('participant', models.ForeignKey(help_text='Participant who authored the contribution', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Point delta (positive, negative, or zero for deferred)')),
                ('status', models.CharField(help_text='Transaction status: AWARDED, DEFERRED, REVOKED, or ADMIN_ADJUST', max_length=50)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for transaction or audit note')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ledger entry timestamp')),
                ('contribution', models.ForeignKey(blank=True, help_text='Associated contribution (nullable for admin adjustments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='core.contribution')),
                ('participant', models.ForeignKey(help_text='Participant receiving or deducted points', on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.BigIntegerField(help_text='Immutable GitHub Repository ID', unique=True)),
                ('owner', models.CharField(help_text='GitHub repository owner/organization', max_length=255)),
                ('name', models.CharField(help_text='GitHub repository name', max_length=255)),
                ('full_name', models.CharField(help_text='GitHub full repository name (owner/name)', max_length=512)),
                ('language', models.CharField(blank=True, default='', help_text='Primary programming language', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this project is active for event submissions')),
                ('description', models.TextField(blank=True, default='', help_text='Repository description')),
            ],
            options={
                'indexes': [models.Index(fields=['is_enabled'], name='project_is_enabled_idx')],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text='Associated tracked project', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project'),
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_id', models.BigIntegerField(help_text='Immutable GitHub Pull Request ID', unique=True)),
                ('number', models.IntegerField(help_text='Pull request number in repository')),
                ('author_github_id', models.BigIntegerField(help_text='GitHub user ID of the PR author')),
                ('merged', models.BooleanField(default=False, help_text='Whether the pull request is merged on GitHub')),
                ('merged_at', models.DateTimeField(blank=True, help_text='Timestamp when merged on GitHub', null=True)),
                ('head_sha', models.CharField(blank=True, default='', help_text='Head commit SHA of the pull request branch', max_length=100)),
                ('author_participant', models.ForeignKey(blank=True, help_text='Registered participant corresponding to PR author, if exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='core.participant')),
                ('repo', models.ForeignKey(help_text='Tracked project the PR was submitted against', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='pull_request',
            field=models.ForeignKey(help_text='Pull request associated with this contribution', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.pullrequest'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action identifier (e.g., admin_point_adjustment, force_merge)', max_length=255)),
                ('target_type', models.CharField(help_text='Target entity type (e.g., Contribution, Participant)', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', help_text='Target entity identifier', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured metadata describing changes or context')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Audit log timestamp')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed action, or null if automated system action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='auditlog_target_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['-total_points'], name='participant_total_pts_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycontributionusage',
            constraint=models.UniqueConstraint(fields=('participant', 'date'), name='unique_participant_date_usage'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['participant', 'created_at'], name='pt_participant_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'AWARDED')), fields=('contribution',), name='unique_awarded_point_transaction_per_contribution'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status'], name='issue_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['points'], name='issue_points_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['difficulty'], name='issue_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status'], name='contrib_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['issue'], name='contrib_issue_idx'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('participant', 'pull_request'), name='unique_participant_pull_request'),
        ),
    ]
