# Generated by Django 6.1.1 on 2026-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issue_created_at_issue_issue_created_at_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_by_github_id',
            field=models.BigIntegerField(blank=True, help_text='GitHub user ID of the issue creator (PRD §22)', null=True),
        ),
    ]
