# Generated by Django 6.1.1 on 2026-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_issue_created_by_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Admin priority override for merge queue processing (PRD §12.3)'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['-is_priority', 'approved_at', 'id'], name='contrib_merge_prio_idx'),
        ),
    ]
