# Generated by Django 6.1.1 on 2026-09-16 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contribution_is_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfig',
            name='leaderboard_frozen_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when leaderboard was frozen', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='merged_count',
            field=models.IntegerField(default=0, help_text='Denormalized count of merged contributions (PRD §15)'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['-total_points', '-merged_count', 'id'], name='participant_leaderboard_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['github_username'], name='participant_username_idx'),
        ),
    ]
