# Generated by Django 6.1.1 on 2026-09-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventconfig_leaderboard_frozen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfig',
            name='allow_partial_daily_points',
            field=models.BooleanField(default=True, help_text='Whether to award partial points up to remaining daily allowance when cap would be exceeded'),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='category_multipliers',
            field=models.JSONField(blank=True, default=dict, help_text='Configurable multipliers by category (e.g. {"feature": 1.5, "bug": 1.0, "docs": 0.8})'),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='per_pr_max_points',
            field=models.IntegerField(default=100, help_text='Maximum points allowed per single pull request'),
        ),
        migrations.CreateModel(
            name='ScoringBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_points', models.IntegerField(help_text='Initial base points evaluated from issue')),
                ('category', models.CharField(help_text='Classification category slug (e.g. feature, bug, docs)', max_length=100)),
                ('category_label', models.CharField(help_text='Human-readable category label (e.g. Feature, Bug Fix, Documentation)', max_length=100)),
                ('multiplier', models.FloatField(default=1.0, help_text='Configured multiplier applied to base points')),
                ('calculated_points', models.IntegerField(help_text='Points after multiplying base points: round(base_points * multiplier)')),
                ('per_pr_cap', models.IntegerField(blank=True, help_text='Per-PR point cap from EventConfig (if enabled)', null=True)),
                ('points_after_pr_cap', models.IntegerField(help_text='Calculated points capped at per_pr_cap')),
                ('daily_points_cap', models.IntegerField(help_text='Daily points cap in effect at evaluation')),
                ('daily_points_before', models.IntegerField(default=0, help_text='Points already earned by participant on this date before this PR')),
                ('daily_allowance_remaining', models.IntegerField(default=0, help_text='Remaining daily point allowance before this PR')),
                ('cap_applied', models.CharField(default='Not reached', help_text='Description of cap applied: Not reached, Daily limit, Daily contribution limit, Per-PR cap', max_length=100)),
                ('final_awarded_points', models.IntegerField(default=0, help_text='Actual points awarded to participant ledger balance')),
                ('farming_signals', models.JSONField(blank=True, default=dict, help_text='Farming pattern and velocity heuristics detected for admin review')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Calculation timestamp')),
                ('contribution', models.OneToOneField(help_text='Associated contribution', on_delete=django.db.models.deletion.CASCADE, related_name='scoring_breakdown', to='core.contribution')),
                ('point_transaction', models.OneToOneField(blank=True, help_text='Linked point transaction in ledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_breakdown', to='core.pointtransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='scoring_created_at_idx'), models.Index(fields=['category'], name='scoring_category_idx')],
            },
        ),
    ]
