# Generated by Django 6.1.1 on 2026-09-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventconfig_allow_partial_daily_points_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['participant', '-created_at'], name='contrib_part_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repo', 'number'], name='pr_repo_number_idx'),
        ),
    ]
