# Generated by Django 6.1.1 on 2026-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contribution_contrib_part_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfig',
            name='event_end_date',
            field=models.DateField(blank=True, help_text='Official event end date (IST)', null=True),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='event_start_date',
            field=models.DateField(blank=True, help_text='Official event start date (IST)', null=True),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='target_branch',
            field=models.CharField(default='main', help_text='Designated target branch for contributions (normally main)', max_length=100),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='base_branch',
            field=models.CharField(blank=True, default='main', help_text='Target base branch of the pull request (normally main)', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventconfig',
            name='allow_partial_daily_points',
            field=models.BooleanField(default=False, help_text='Whether to award partial points up to remaining daily allowance (False: PR either earns full score or 0 if exceeding 120 cap)'),
        ),
        migrations.AlterField(
            model_name='eventconfig',
            name='max_points_per_day',
            field=models.IntegerField(default=120, help_text='Daily points cap per participant (HackIT CommitRush rule: 120 points/day)'),
        ),
        migrations.AlterField(
            model_name='eventconfig',
            name='per_pr_max_points',
            field=models.IntegerField(default=50, help_text='Maximum points allowed per single pull request (Master=50)'),
        ),
    ]
