# Generated by Django 6.1.1 on 2026-09-24 15:13

import django.utils.timezone
from django.db import migrations, models


def update_event_config_daily_cap(apps, schema_editor):
    EventConfig = apps.get_model('core', 'EventConfig')
    EventConfig.objects.filter(max_points_per_day=500).update(max_points_per_day=120)


def reverse_update_event_config_daily_cap(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contribution_contrib_part_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Issue updated timestamp on GitHub'),
        ),
        migrations.AlterField(
            model_name='eventconfig',
            name='max_points_per_day',
            field=models.IntegerField(default=120, help_text='Daily points cap per participant'),
        ),
        migrations.RunPython(
            code=update_event_config_daily_cap,
            reverse_code=reverse_update_event_config_daily_cap,
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category'], name='issue_category_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'number'], name='issue_proj_num_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-updated_at'], name='issue_updated_at_idx'),
        ),
    ]
